### ISSUE TITLE
named import does not work

### ISSUE THREAD

**Issue by xatian** [taoqf/node-html-parser#53]
The first usage-example does not work for me.
I created a new file in an empty directory, pasted your code and tried to run it.

```
$> npm init
....
$> npm install node-html-parser
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ node-html-parser@1.2.19
added 2 packages from 3 contributors and audited 2 packages in 0.409s
found 0 vulnerabilities

$> vim test.mjs
... (pasted the first usage-example) ...
$> node test.mjs
import { parse } from 'node-html-parser';
         ^^^^^
SyntaxError: The requested module 'node-html-parser' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'node-html-parser';
const { parse } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:135:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)

$> node --version
v14.4.0
```

Did I do something wrong?
Thank you!

**Comment by taoqf** [comment]
I wish [this](https://github.com/taoqf/node-html-parser/commit/c3437a83ac52bfbdf99442ce0f01429381b15b4b) will help you.
