### ISSUE TITLE
insertAdjacentHTML not working when having flat HTML

### ISSUE THREAD

**Issue by KeizerDev** [taoqf/node-html-parser#56]
With for example this HTML:
```
<body>
lorem ipsum
<img src="..." alt="..." />
lorem ipsum
<h2 style="text-align: center;">more text</h2>
<h5 style="text-align: center;">more text</h2>
<h5 style="text-align: center;">more text</h2>
</body>
```
and this code
```
    var root = HTMLParser.parse(text);
    var ele = root.querySelector('h2');
    ele.insertAdjacentHTML("afterend", "<div></div>")
    console.log(root.toString())
```
The div will be added like this `<div></div></body>`, however it should be added after the h2. 

When I don't add a parent tag `insertAdjacentHTML` will raise an error, probably because of this https://github.com/taoqf/node-html-parser/commit/a72c0da9eeb02e575f5e3e55ba69931be858e8f6#diff-3ba29b891fcc8c2d131ae8f408ae8177R522-R523

Error:
```
node-html-parser/dist/nodes/html.js:581
                _this.parentNode.appendChild(n);
                                 ^

TypeError: Cannot read property 'appendChild' of null
    at node-html-parser/dist/nodes/html.js:581:34
    at Array.forEach (<anonymous>)
    at HTMLElement.insertAdjacentHTML (node-html-parser/dist/nodes/html.js:580:26)
```

**Comment by taoqf** [comment]
Sorry I don't have much time to do with this, pr is welcomed.
